In [17]:
import numpy as np
from copy import deepcopy

In [2]:
Psi_proj = np.ones([8, 8])/8
I = np.identity(8) 
print(Psi_proj)
print(I)

[[0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [5]:
a = np.zeros(8)
a[::2] = 1
a[1::2] = -1
a

array([ 1., -1.,  1., -1.,  1., -1.,  1., -1.])

In [6]:
Z = np.zeros((8, 8))
np.fill_diagonal(Z, a)
print(Z)

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]]


In [7]:
G = np.dot(2*Psi_proj - I, Z)

In [8]:
G

array([[-0.75, -0.25,  0.25, -0.25,  0.25, -0.25,  0.25, -0.25],
       [ 0.25,  0.75,  0.25, -0.25,  0.25, -0.25,  0.25, -0.25],
       [ 0.25, -0.25, -0.75, -0.25,  0.25, -0.25,  0.25, -0.25],
       [ 0.25, -0.25,  0.25,  0.75,  0.25, -0.25,  0.25, -0.25],
       [ 0.25, -0.25,  0.25, -0.25, -0.75, -0.25,  0.25, -0.25],
       [ 0.25, -0.25,  0.25, -0.25,  0.25,  0.75,  0.25, -0.25],
       [ 0.25, -0.25,  0.25, -0.25,  0.25, -0.25, -0.75, -0.25],
       [ 0.25, -0.25,  0.25, -0.25,  0.25, -0.25,  0.25,  0.75]])

In [13]:
psi = np.array([ 1., 0., 1., 0.,  1., 0.,  0., 1.]) / 2

In [14]:
psi

array([0.5, 0. , 0.5, 0. , 0.5, 0. , 0. , 0.5])

In [19]:
current_psi = deepcopy(psi)

for i in range(10):
    current_psi = np.dot(G, current_psi)
    print(i, current_psi)

0 [-0.25  0.25 -0.25  0.25 -0.25  0.25  0.25  0.75]
1 [-0.25 -0.25 -0.25 -0.25 -0.25 -0.25 -0.75  0.25]
2 [ 0.  -0.5  0.  -0.5  0.  -0.5  0.5  0. ]
3 [0.5 0.  0.5 0.  0.5 0.  0.  0.5]
4 [-0.25  0.25 -0.25  0.25 -0.25  0.25  0.25  0.75]
5 [-0.25 -0.25 -0.25 -0.25 -0.25 -0.25 -0.75  0.25]
6 [ 0.  -0.5  0.  -0.5  0.  -0.5  0.5  0. ]
7 [0.5 0.  0.5 0.  0.5 0.  0.  0.5]
8 [-0.25  0.25 -0.25  0.25 -0.25  0.25  0.25  0.75]
9 [-0.25 -0.25 -0.25 -0.25 -0.25 -0.25 -0.75  0.25]


In [15]:
np.dot(G, psi)

array([-0.25,  0.25, -0.25,  0.25, -0.25,  0.25,  0.25,  0.75])

In [16]:
np.dot(G, np.dot(G, psi))

array([-0.25, -0.25, -0.25, -0.25, -0.25, -0.25, -0.75,  0.25])

In [20]:
0.75**2

0.5625

In [21]:
0.25**2

0.0625