In [1]:
import numpy as np
from context import tools as t

In [11]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)

In [12]:
c = np.tensordot(a, b, axes=([0, 1],[1, 0]))

In [13]:
c

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [14]:
d = np.zeros((5, 2))
for i in range(5):
    for j in range(2):
        for k in range(3):
            for n in range(4):
                d[i,j] += a[k,n,i] * b[n,k,j]

In [15]:
c == d

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [27]:
a = t.normalize([1+2j, 2+2j])
b = t.normalize([2+3j, 1+5j, 9+2j, 9+4j])
b = b.reshape(2, 2)
print('a')
print(a)
print('b')
print(b)

a
[0.2773501+0.5547002j 0.5547002+0.5547002j]
b
[[0.13453456+0.20180184j 0.06726728+0.3363364j ]
 [0.60540551+0.13453456j 0.60540551+0.26906912j]]


In [30]:
# expected
print(a[0]*b[0][0]+a[1]*b[1][0], a[0]*b[0][1]+a[1]*b[1][1])

(0.18656586541256379+0.541041009696435j) (0.018656586541256376+0.6156673558614605j)


In [28]:
np.einsum('i,ij', a, b)

array([0.18656587+0.54104101j, 0.01865659+0.61566736j])

In [20]:
np.einsum('ij,j', b, a)

ValueError: einstein sum subscripts string contains too many subscripts for operand 0

In [23]:
np.einsum('i', a)

array([0.2773501+0.5547002j, 0.5547002+0.5547002j])

In [24]:
np.shape(a)

(2,)

In [26]:
b.shape

(4,)

In [4]:
a = t.normalize([1+2j, 2+2j])
b = t.normalize([2+3j, 1+5j, 9+2j, 9+4j])
b = b.reshape(2, 2)
print(np.absolute(np.einsum('i,ij', a, b))**2)
print(np.absolute(np.einsum('i,ij', np.conjugate(a), b))**2)

[0.3275322  0.37939436]
[0.39157675 0.49356074]


In [5]:
a = np.array([1, 2])
b = np.array([2j, 1j, 1, 9])
b = b.reshape(2, 2)
print(a)
print(b)
print(b)
state = np.einsum('i,ij', a, b)
print(state)

[1 2]
[[0.+2.j 0.+1.j]
 [1.+0.j 9.+0.j]]
[[0.+2.j 0.+1.j]
 [1.+0.j 9.+0.j]]
[ 2.+2.j 18.+1.j]


In [8]:
print(a[0]*b[0][0] + a[1]*b[1][0])
print(a[0]*b[0][1] + a[1]*b[1][1])

(2+2j)
(18+1j)
